### ISSUE TITLE
Units for tos incorrect

### ISSUE THREAD

**Issue by ehogan** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#90]
The value of the `processing` attribute for `tos` (http://clipc-services.ceda.ac.uk/dreq/u/47954cc8-bb0b-11e6-8316-5980f7b176d1.html) says `Note change from CMIP5 K to CMIP6 C`, but the units for `tos` are still `K` (see http://clipc-services.ceda.ac.uk/dreq/u/0e5d376315a376cd2b1e37f440fe43d3.html).

**Comment by martinjuckes** [comment]
Fixed

**Comment by ehogan** [comment]
Thanks for the quick response! :)

**Comment by ehogan** [comment]
Hi @martinjuckes, it appears the units for `tos` are still `K`, see http://clipc-services.ceda.ac.uk/dreq/u/0e5d376315a376cd2b1e37f440fe43d3.html; would it be possible for you to fix this?

**Comment by ehogan** [comment]
This issue is still present; @martinjuckes would it be possible for you to provide an update, please? :)

**Comment by matthew-mizielinski** [comment]
I've confirmed that this issue is still present in v01.00.16 of the data request (see [here](http://clipc-services.ceda.ac.uk/dreq/u/0e5d376315a376cd2b1e37f440fe43d3.html)).

@martinjuckes, could you please re-open this issue.
